### ISSUE TITLE
Make arrays dynamic

### ISSUE THREAD

**Issue by mhalden** [openbsm/bsmtrace#8]
Hi,

We have a lot of filesystems defined in the configuration of bsmtrace on some systems and we have been running into bsmtrace crashing when some of the arrays run out of storage. Arrays should preferably be made to allocate memory dynamically.

We currently use [this patch](https://gist.github.com/mhalden/0e78063a1417fd487fbfc2c56bb16850) on our systems to get around this problem.

**Comment by csjayp** [comment]
Hey,

We are changing how objects are matched based on regular expression to
hopefully simplify some stuff.. but I should be able to merge this into
master pretty easily.

Thanks for the patch!

**Comment by mhalden** [comment]
Thanks, if you want I can create a PR for the patch.

**Comment by csjayp** [comment]
That would be awesome!

**Comment by mhalden** [comment]
Just created #9

**Comment by csjayp** [comment]
PR merged and contributors updated, thanks!
